export const dishesSeed = [
  // ──────────────────────────────────────────────
  // PÓS-TREINO
  // ──────────────────────────────────────────────
  {
    name: 'Tapioca com Ovos e Abacate',
    description: 'Tapioca recheada com ovos mexidos e fatias de abacate',
    meal_slot: 'post_workout',
    tags: ['quick', 'high_protein'],
    prep_time_min: 15,
    is_batch_cookable: false,
    servings: 1,
    ingredients: [
      { ingredient_id: 40, quantity_g: 50, notes: 'hidratada' },
      { ingredient_id: 8, quantity_g: 150, notes: '3 ovos' },
      { ingredient_id: 51, quantity_g: 50 },
      { ingredient_id: 49, quantity_g: 5 },
    ],
  },
  {
    name: 'Batata Doce com Frango Desfiado',
    description: 'Batata doce assada com frango desfiado temperado',
    meal_slot: 'post_workout',
    tags: ['high_protein', 'batch_cook'],
    prep_time_min: 40,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 37, quantity_g: 200 },
      { ingredient_id: 1, quantity_g: 150 },
      { ingredient_id: 49, quantity_g: 10 },
      { ingredient_id: 81, quantity_g: 2 },
    ],
  },
  {
    name: 'Smoothie Proteico de Frutas',
    description: 'Smoothie com whey, banana, morango e leite de coco',
    meal_slot: 'post_workout',
    tags: ['quick', 'high_protein'],
    prep_time_min: 5,
    is_batch_cookable: false,
    servings: 1,
    ingredients: [
      { ingredient_id: 15, quantity_g: 30 },
      { ingredient_id: 43, quantity_g: 100 },
      { ingredient_id: 68, quantity_g: 80 },
      { ingredient_id: 62, quantity_g: 200 },
    ],
  },
  {
    name: 'Panqueca de Farinha de Arroz com Whey',
    description: 'Panquecas proteicas com farinha de arroz e whey',
    meal_slot: 'post_workout',
    tags: ['high_protein', 'batch_cook'],
    prep_time_min: 20,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 46, quantity_g: 50 },
      { ingredient_id: 15, quantity_g: 30 },
      { ingredient_id: 8, quantity_g: 100, notes: '2 ovos' },
      { ingredient_id: 43, quantity_g: 50 },
      { ingredient_id: 50, quantity_g: 5 },
    ],
  },
  {
    name: 'Bowl de Aveia com Frutas e Castanhas',
    description: 'Aveia sem glúten com leite de coco, frutas vermelhas e castanha do Pará',
    meal_slot: 'post_workout',
    tags: ['quick', 'batch_cook'],
    prep_time_min: 10,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 41, quantity_g: 50 },
      { ingredient_id: 62, quantity_g: 150 },
      { ingredient_id: 69, quantity_g: 50 },
      { ingredient_id: 52, quantity_g: 15, notes: '3 unidades' },
      { ingredient_id: 91, quantity_g: 2 },
    ],
  },

  // ──────────────────────────────────────────────
  // ALMOÇO
  // ──────────────────────────────────────────────
  {
    name: 'Frango Grelhado com Arroz e Brócolis',
    description: 'Peito de frango grelhado com arroz integral e brócolis no vapor',
    meal_slot: 'lunch',
    tags: ['high_protein', 'batch_cook', 'classic'],
    prep_time_min: 35,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 1, quantity_g: 180 },
      { ingredient_id: 38, quantity_g: 150 },
      { ingredient_id: 16, quantity_g: 100 },
      { ingredient_id: 49, quantity_g: 10 },
      { ingredient_id: 81, quantity_g: 2 },
    ],
  },
  {
    name: 'Salmão com Batata Doce e Aspargos',
    description: 'Salmão assado com batata doce e aspargos grelhados',
    meal_slot: 'lunch',
    tags: ['high_protein', 'omega3'],
    prep_time_min: 30,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 5, quantity_g: 150 },
      { ingredient_id: 37, quantity_g: 150 },
      { ingredient_id: 27, quantity_g: 100 },
      { ingredient_id: 49, quantity_g: 10 },
      { ingredient_id: 78, quantity_g: 20 },
    ],
  },
  {
    name: 'Alcatra com Purê de Abóbora e Salada',
    description: 'Alcatra grelhada com purê de abóbora e salada verde',
    meal_slot: 'lunch',
    tags: ['high_protein', 'batch_cook'],
    prep_time_min: 40,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 4, quantity_g: 150 },
      { ingredient_id: 31, quantity_g: 150 },
      { ingredient_id: 19, quantity_g: 30 },
      { ingredient_id: 23, quantity_g: 50 },
      { ingredient_id: 49, quantity_g: 10 },
    ],
  },
  {
    name: 'Tilápia com Arroz e Vagem',
    description: 'Tilápia assada com arroz integral e vagem refogada',
    meal_slot: 'lunch',
    tags: ['high_protein', 'low_fat', 'batch_cook'],
    prep_time_min: 30,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 6, quantity_g: 180 },
      { ingredient_id: 38, quantity_g: 150 },
      { ingredient_id: 28, quantity_g: 100 },
      { ingredient_id: 36, quantity_g: 5 },
      { ingredient_id: 49, quantity_g: 8 },
    ],
  },
  {
    name: 'Almôndegas de Peru com Arroz e Couve',
    description: 'Almôndegas de peru ao molho de tomate com arroz e couve refogada',
    meal_slot: 'lunch',
    tags: ['high_protein', 'batch_cook'],
    prep_time_min: 45,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 10, quantity_g: 180, notes: 'moído' },
      { ingredient_id: 38, quantity_g: 150 },
      { ingredient_id: 18, quantity_g: 80 },
      { ingredient_id: 102, quantity_g: 30 },
      { ingredient_id: 35, quantity_g: 20 },
    ],
  },
  {
    name: 'Carne Moída com Mandioca e Salada',
    description: 'Carne moída refogada com mandioca cozida e salada de alface e tomate',
    meal_slot: 'lunch',
    tags: ['high_protein', 'batch_cook'],
    prep_time_min: 35,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 3, quantity_g: 150 },
      { ingredient_id: 42, quantity_g: 150 },
      { ingredient_id: 25, quantity_g: 30 },
      { ingredient_id: 23, quantity_g: 50 },
      { ingredient_id: 49, quantity_g: 8 },
    ],
  },

  // ──────────────────────────────────────────────
  // LANCHE
  // ──────────────────────────────────────────────
  {
    name: 'Mix de Castanhas e Sementes',
    description: 'Castanha do Pará, castanha de caju, amêndoas e sementes de abóbora',
    meal_slot: 'snack',
    tags: ['quick', 'portable'],
    prep_time_min: 2,
    is_batch_cookable: false,
    servings: 1,
    ingredients: [
      { ingredient_id: 52, quantity_g: 15 },
      { ingredient_id: 53, quantity_g: 15 },
      { ingredient_id: 55, quantity_g: 15 },
      { ingredient_id: 58, quantity_g: 10 },
    ],
  },
  {
    name: 'Queijo de Búfala com Tomate e Azeite',
    description: 'Caprese com queijo de búfala, tomate e azeite',
    meal_slot: 'snack',
    tags: ['quick', 'high_protein'],
    prep_time_min: 5,
    is_batch_cookable: false,
    servings: 1,
    ingredients: [
      { ingredient_id: 64, quantity_g: 60 },
      { ingredient_id: 23, quantity_g: 80 },
      { ingredient_id: 49, quantity_g: 10 },
      { ingredient_id: 88, quantity_g: 3 },
    ],
  },
  {
    name: 'Smoothie de Proteína e Coco',
    description: 'Whey com leite de coco, cacau e banana',
    meal_slot: 'snack',
    tags: ['quick', 'high_protein'],
    prep_time_min: 5,
    is_batch_cookable: false,
    servings: 1,
    ingredients: [
      { ingredient_id: 15, quantity_g: 30 },
      { ingredient_id: 62, quantity_g: 200 },
      { ingredient_id: 93, quantity_g: 10 },
      { ingredient_id: 43, quantity_g: 80 },
    ],
  },
  {
    name: 'Iogurte de Coco com Frutas e Chia',
    description: 'Iogurte de coco com morangos, mirtilo e sementes de chia',
    meal_slot: 'snack',
    tags: ['quick'],
    prep_time_min: 5,
    is_batch_cookable: false,
    servings: 1,
    ingredients: [
      { ingredient_id: 67, quantity_g: 150 },
      { ingredient_id: 68, quantity_g: 50 },
      { ingredient_id: 69, quantity_g: 30 },
      { ingredient_id: 56, quantity_g: 10 },
    ],
  },
  {
    name: 'Ovos Cozidos com Abacate',
    description: 'Ovos cozidos com abacate amassado e sal do Himalaia',
    meal_slot: 'snack',
    tags: ['quick', 'high_protein', 'portable'],
    prep_time_min: 15,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 8, quantity_g: 150, notes: '3 ovos' },
      { ingredient_id: 51, quantity_g: 80 },
      { ingredient_id: 81, quantity_g: 2 },
    ],
  },

  // ──────────────────────────────────────────────
  // JANTAR
  // ──────────────────────────────────────────────
  {
    name: 'Lasanha de Abobrinha com Carne Moída',
    description: 'Fatias de abobrinha substituindo a massa, com carne moída e queijo de cabra',
    meal_slot: 'dinner',
    tags: ['batch_cook', 'low_carb'],
    prep_time_min: 50,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 20, quantity_g: 200 },
      { ingredient_id: 3, quantity_g: 150 },
      { ingredient_id: 65, quantity_g: 30 },
      { ingredient_id: 102, quantity_g: 30 },
      { ingredient_id: 49, quantity_g: 5 },
    ],
  },
  {
    name: 'Salmão com Inhame e Salada Verde',
    description: 'Salmão grelhado com inhame cozido e mix de folhas',
    meal_slot: 'dinner',
    tags: ['high_protein', 'omega3', 'batch_cook'],
    prep_time_min: 35,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 5, quantity_g: 150 },
      { ingredient_id: 44, quantity_g: 150 },
      { ingredient_id: 19, quantity_g: 30 },
      { ingredient_id: 17, quantity_g: 30 },
      { ingredient_id: 49, quantity_g: 8 },
    ],
  },
  {
    name: 'Frango com Arroz e Legumes',
    description: 'Coxa de frango assada com arroz integral e legumes salteados',
    meal_slot: 'dinner',
    tags: ['batch_cook', 'classic'],
    prep_time_min: 45,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 2, quantity_g: 180 },
      { ingredient_id: 38, quantity_g: 150 },
      { ingredient_id: 22, quantity_g: 50 },
      { ingredient_id: 20, quantity_g: 50 },
      { ingredient_id: 30, quantity_g: 30 },
    ],
  },
  {
    name: 'Berinjela Recheada com Peru',
    description: 'Berinjela assada recheada com peru moído e temperos',
    meal_slot: 'dinner',
    tags: ['batch_cook', 'low_carb'],
    prep_time_min: 40,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 33, quantity_g: 200 },
      { ingredient_id: 10, quantity_g: 150, notes: 'moído' },
      { ingredient_id: 23, quantity_g: 50 },
      { ingredient_id: 35, quantity_g: 20 },
      { ingredient_id: 84, quantity_g: 3 },
    ],
  },
  {
    name: 'Lombo Suíno com Batata Doce e Couve',
    description: 'Lombo suíno assado com batata doce e couve refogada no alho',
    meal_slot: 'dinner',
    tags: ['batch_cook', 'high_protein'],
    prep_time_min: 45,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 11, quantity_g: 180 },
      { ingredient_id: 37, quantity_g: 200 },
      { ingredient_id: 18, quantity_g: 80 },
      { ingredient_id: 36, quantity_g: 5 },
      { ingredient_id: 49, quantity_g: 8 },
    ],
  },
  {
    name: 'Camarão com Mandioca e Salada',
    description: 'Camarão salteado com mandioca cozida e salada tropical',
    meal_slot: 'dinner',
    tags: ['batch_cook'],
    prep_time_min: 30,
    is_batch_cookable: true,
    servings: 1,
    ingredients: [
      { ingredient_id: 7, quantity_g: 180 },
      { ingredient_id: 42, quantity_g: 150 },
      { ingredient_id: 71, quantity_g: 50 },
      { ingredient_id: 25, quantity_g: 30 },
      { ingredient_id: 49, quantity_g: 8 },
    ],
  },
];
