export const exercisesSeed = [
  // ──────────────────────────────────────────────
  // WEIGHTLIFTING — CHEST
  // ──────────────────────────────────────────────
  { name: 'dumbbell_bench_press', name_pt: 'Supino com Halteres', modality: 'weightlifting', primary_muscles: ['chest'], secondary_muscles: ['triceps', 'anterior_deltoid'], equipment: ['dumbbell', 'bench'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Desça controlado até os halteres alinharem com o peito. Empurre explosivo, contraindo o peitoral no topo.', tags: ['push', 'horizontal'] },
  { name: 'incline_dumbbell_press', name_pt: 'Supino Inclinado com Halteres', modality: 'weightlifting', primary_muscles: ['chest'], secondary_muscles: ['anterior_deltoid', 'triceps'], equipment: ['dumbbell', 'bench'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Banco a 30-45°. Foco na porção clavicular do peitoral. Não deixe os cotovelos abrirem demais.', tags: ['push', 'horizontal'] },
  { name: 'decline_dumbbell_press', name_pt: 'Supino Declinado com Halteres', modality: 'weightlifting', primary_muscles: ['chest'], secondary_muscles: ['triceps'], equipment: ['dumbbell', 'bench'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Banco a -15°. Ênfase na porção esternal do peitoral.', tags: ['push', 'horizontal'] },
  { name: 'dumbbell_fly', name_pt: 'Crucifixo com Halteres', modality: 'weightlifting', primary_muscles: ['chest'], secondary_muscles: ['anterior_deltoid'], equipment: ['dumbbell', 'bench'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Abra os braços em arco controlado. Sinta o alongamento do peitoral. Cotovelos levemente flexionados.', tags: ['push', 'horizontal'] },
  { name: 'cable_crossover', name_pt: 'Crossover no Cabo', modality: 'weightlifting', primary_muscles: ['chest'], secondary_muscles: ['anterior_deltoid'], equipment: ['cable'], movement_type: 'isolation', difficulty: 'intermediate', video_url: '', execution_tips: 'Corpo levemente inclinado à frente. Cruze as mãos na frente do corpo, apertando o peitoral.', tags: ['push'] },
  { name: 'close_grip_bench_press', name_pt: 'Supino Pegada Fechada', modality: 'weightlifting', primary_muscles: ['triceps', 'chest'], secondary_muscles: ['anterior_deltoid'], equipment: ['barbell', 'bench'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Mãos na largura dos ombros. Cotovelos junto ao corpo. Foco no tríceps.', tags: ['push', 'horizontal'] },

  // ──────────────────────────────────────────────
  // WEIGHTLIFTING — BACK
  // ──────────────────────────────────────────────
  { name: 'lat_pulldown', name_pt: 'Puxada na Polia', modality: 'weightlifting', primary_muscles: ['lats', 'back'], secondary_muscles: ['biceps', 'rhomboids'], equipment: ['cable'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Puxe a barra até o peito, apertando as escápulas. Volte controlado.', tags: ['pull', 'vertical'] },
  { name: 'barbell_row', name_pt: 'Remada com Barra', modality: 'weightlifting', primary_muscles: ['back', 'lats'], secondary_muscles: ['biceps', 'rhomboids', 'traps'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Tronco a 45°, core firme. Puxe a barra até o abdômen. Escápulas retraídas.', tags: ['pull', 'horizontal'] },
  { name: 'seated_cable_row', name_pt: 'Remada Sentada no Cabo', modality: 'weightlifting', primary_muscles: ['back', 'rhomboids'], secondary_muscles: ['biceps', 'lats'], equipment: ['cable'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Mantenha o tronco ereto. Puxe até o abdômen, apertando as escápulas no final.', tags: ['pull', 'horizontal'] },
  { name: 'chest_supported_row', name_pt: 'Remada com Apoio no Peito', modality: 'weightlifting', primary_muscles: ['back', 'rhomboids'], secondary_muscles: ['biceps'], equipment: ['dumbbell', 'bench'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Apoie o peito no banco inclinado. Elimina o impulso do tronco, isolando as costas.', tags: ['pull', 'horizontal'] },
  { name: 'pendlay_row', name_pt: 'Remada Pendlay', modality: 'weightlifting', primary_muscles: ['back', 'lats'], secondary_muscles: ['biceps', 'traps'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Barra parte do chão a cada rep. Tronco paralelo ao solo. Explosivo na subida.', tags: ['pull', 'horizontal'] },
  { name: 'pullup', name_pt: 'Barra Fixa', modality: 'weightlifting', primary_muscles: ['lats', 'back'], secondary_muscles: ['biceps', 'forearms'], equipment: ['pullup_bar'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Pegada pronada. Puxe o peito até a barra. Desça controlado até extensão completa.', tags: ['pull', 'vertical'] },

  // ──────────────────────────────────────────────
  // WEIGHTLIFTING — SHOULDERS
  // ──────────────────────────────────────────────
  { name: 'face_pull', name_pt: 'Face Pull', modality: 'weightlifting', primary_muscles: ['posterior_deltoid', 'traps'], secondary_muscles: ['rhomboids'], equipment: ['cable'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Puxe a corda na direção do rosto. Rotação externa no final. Essencial para saúde do ombro.', tags: ['pull'] },
  { name: 'lateral_raise', name_pt: 'Elevação Lateral', modality: 'weightlifting', primary_muscles: ['lateral_deltoid'], secondary_muscles: ['traps'], equipment: ['dumbbell'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Eleve até a altura dos ombros. Leve inclinação à frente. Controlado na descida.', tags: ['push'] },
  { name: 'rear_delt_fly', name_pt: 'Crucifixo Inverso', modality: 'weightlifting', primary_muscles: ['posterior_deltoid'], secondary_muscles: ['rhomboids', 'traps'], equipment: ['dumbbell'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Incline o tronco. Abra os braços em arco, apertando as escápulas.', tags: ['pull'] },
  { name: 'overhead_press', name_pt: 'Desenvolvimento', modality: 'weightlifting', primary_muscles: ['shoulders', 'anterior_deltoid'], secondary_muscles: ['triceps', 'traps'], equipment: ['dumbbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Empurre os halteres acima da cabeça. Core firme, sem arquear as costas.', tags: ['push', 'vertical'] },

  // ──────────────────────────────────────────────
  // WEIGHTLIFTING — ARMS
  // ──────────────────────────────────────────────
  { name: 'hammer_curl', name_pt: 'Rosca Martelo', modality: 'weightlifting', primary_muscles: ['biceps'], secondary_muscles: ['forearms'], equipment: ['dumbbell'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Pegada neutra. Cotovelos fixos. Foco no braquiorradial.', tags: ['pull'] },
  { name: 'ez_bar_curl', name_pt: 'Rosca com Barra EZ', modality: 'weightlifting', primary_muscles: ['biceps'], secondary_muscles: ['forearms'], equipment: ['ez_bar'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Cotovelos fixos ao lado do corpo. Pegada na curva da barra para conforto do punho.', tags: ['pull'] },
  { name: 'cable_curl', name_pt: 'Rosca no Cabo', modality: 'weightlifting', primary_muscles: ['biceps'], secondary_muscles: ['forearms'], equipment: ['cable'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Tensão constante do cabo. Cotovelos fixos. Contraia no topo.', tags: ['pull'] },
  { name: 'concentration_curl', name_pt: 'Rosca Concentrada', modality: 'weightlifting', primary_muscles: ['biceps'], secondary_muscles: [], equipment: ['dumbbell'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Cotovelo apoiado na coxa. Isole o bíceps completamente. Pico de contração no topo.', tags: ['pull'] },
  { name: 'spider_curl', name_pt: 'Rosca Spider', modality: 'weightlifting', primary_muscles: ['biceps'], secondary_muscles: [], equipment: ['dumbbell', 'bench'], movement_type: 'isolation', difficulty: 'intermediate', video_url: '', execution_tips: 'Deite no banco inclinado com braços pendentes. Tensão constante no bíceps.', tags: ['pull'] },
  { name: 'tricep_pushdown', name_pt: 'Tríceps no Cabo', modality: 'weightlifting', primary_muscles: ['triceps'], secondary_muscles: [], equipment: ['cable'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Cotovelos fixos ao lado do corpo. Extensão completa. Aperte no final.', tags: ['push'] },
  { name: 'overhead_tricep_extension', name_pt: 'Extensão de Tríceps Acima da Cabeça', modality: 'weightlifting', primary_muscles: ['triceps'], secondary_muscles: [], equipment: ['cable', 'dumbbell'], movement_type: 'isolation', difficulty: 'intermediate', video_url: '', execution_tips: 'Braços acima da cabeça. Flexione até 90° e estenda completamente.', tags: ['push'] },
  { name: 'skull_crusher', name_pt: 'Tríceps Testa', modality: 'weightlifting', primary_muscles: ['triceps'], secondary_muscles: [], equipment: ['ez_bar', 'bench'], movement_type: 'isolation', difficulty: 'intermediate', video_url: '', execution_tips: 'Desça a barra até a testa. Cotovelos apontando para o teto. Extensão completa.', tags: ['push'] },
  { name: 'dip', name_pt: 'Mergulho (Paralelas)', modality: 'weightlifting', primary_muscles: ['triceps', 'chest'], secondary_muscles: ['anterior_deltoid'], equipment: ['dip_bar'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Corpo ereto para tríceps, inclinado para peito. Desça até 90° nos cotovelos.', tags: ['push', 'vertical'] },

  // ──────────────────────────────────────────────
  // WEIGHTLIFTING — LEGS
  // ──────────────────────────────────────────────
  { name: 'barbell_squat', name_pt: 'Agachamento com Barra', modality: 'weightlifting', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['hamstrings', 'core'], equipment: ['barbell', 'squat_rack'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Desça até paralelo ou abaixo. Joelhos alinhados com os pés. Core firme.', tags: ['squat'] },
  { name: 'leg_press', name_pt: 'Leg Press', modality: 'weightlifting', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['hamstrings'], equipment: ['leg_press'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Pés na largura dos ombros. Desça até 90° nos joelhos. Não trave os joelhos na extensão.', tags: ['squat'] },
  { name: 'romanian_deadlift', name_pt: 'Levantamento Terra Romeno', modality: 'weightlifting', primary_muscles: ['hamstrings', 'glutes'], secondary_muscles: ['back', 'core'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Joelhos levemente flexionados. Empurre o quadril para trás. Sinta o alongamento dos posteriores.', tags: ['hinge'] },
  { name: 'leg_curl', name_pt: 'Mesa Flexora', modality: 'weightlifting', primary_muscles: ['hamstrings'], secondary_muscles: [], equipment: ['machine'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Flexione até o calcanhar tocar o glúteo. Negativa lenta de 3s.', tags: ['hinge'] },
  { name: 'leg_extension', name_pt: 'Cadeira Extensora', modality: 'weightlifting', primary_muscles: ['quadriceps'], secondary_muscles: [], equipment: ['machine'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Extensão completa. Segure no topo 1-2s. Controle a descida.', tags: ['squat'] },
  { name: 'hip_thrust', name_pt: 'Hip Thrust', modality: 'weightlifting', primary_muscles: ['glutes'], secondary_muscles: ['hamstrings'], equipment: ['barbell', 'bench'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Costas apoiadas no banco. Empurre o quadril para cima. Aperte o glúteo no topo.', tags: ['hinge'] },
  { name: 'calf_raise', name_pt: 'Elevação de Panturrilha', modality: 'weightlifting', primary_muscles: ['calves'], secondary_muscles: [], equipment: ['machine'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Amplitude completa. Segure no topo. Alongue na descida. Reps altas (15-20).', tags: [] },
  { name: 'bulgarian_split_squat', name_pt: 'Agachamento Búlgaro', modality: 'weightlifting', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['hamstrings', 'core'], equipment: ['dumbbell', 'bench'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Pé traseiro no banco. Desça até o joelho quase tocar o chão. Tronco ereto.', tags: ['squat'] },
  { name: 'goblet_squat', name_pt: 'Goblet Squat', modality: 'weightlifting', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['core'], equipment: ['dumbbell'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Segure o halter junto ao peito. Cotovelos entre os joelhos na descida.', tags: ['squat'] },
  { name: 'sumo_deadlift', name_pt: 'Levantamento Terra Sumo', modality: 'weightlifting', primary_muscles: ['glutes', 'hamstrings'], secondary_muscles: ['quadriceps', 'back'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Pés largos, pontas para fora. Quadril baixo. Empurre o chão com os pés.', tags: ['hinge'] },
  { name: 'shrug', name_pt: 'Encolhimento', modality: 'weightlifting', primary_muscles: ['traps'], secondary_muscles: [], equipment: ['dumbbell'], movement_type: 'isolation', difficulty: 'beginner', video_url: '', execution_tips: 'Eleve os ombros retos para cima. Segure 2s no topo. Sem rotação.', tags: [] },

  // ──────────────────────────────────────────────
  // CROSSFIT (~25)
  // ──────────────────────────────────────────────
  { name: 'thruster', name_pt: 'Thruster', modality: 'crossfit', primary_muscles: ['quadriceps', 'shoulders'], secondary_muscles: ['glutes', 'triceps', 'core'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Front squat + push press em um movimento fluido. Receba a barra em posição de front rack.', tags: ['squat', 'push'] },
  { name: 'wall_ball', name_pt: 'Wall Ball', modality: 'crossfit', primary_muscles: ['quadriceps', 'shoulders'], secondary_muscles: ['glutes', 'core'], equipment: ['medicine_ball'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Agache profundo com a bola. Exploda e lance no alvo. Ritmo constante.', tags: ['squat', 'push'] },
  { name: 'box_jump', name_pt: 'Box Jump', modality: 'crossfit', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['calves', 'hamstrings'], equipment: ['box'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Use os braços para impulso. Aterrisse suave com joelhos flexionados. Abra o quadril no topo.', tags: ['squat'] },
  { name: 'burpee', name_pt: 'Burpee', modality: 'crossfit', primary_muscles: ['chest', 'quadriceps'], secondary_muscles: ['shoulders', 'core', 'triceps'], equipment: [], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Peito toca o chão. Pule explosivo no final. Mantenha o ritmo.', tags: ['push'] },
  { name: 'toes_to_bar', name_pt: 'Toes to Bar', modality: 'crossfit', primary_muscles: ['core'], secondary_muscles: ['lats', 'forearms'], equipment: ['pullup_bar'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Use o kip para gerar momentum. Toque os pés na barra. Controle o balanço.', tags: [] },
  { name: 'kipping_pullup', name_pt: 'Pull-up com Kipping', modality: 'crossfit', primary_muscles: ['lats', 'back'], secondary_muscles: ['biceps', 'core'], equipment: ['pullup_bar'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Balanço de quadril gera o impulso. Queixo acima da barra. Cicle com eficiência.', tags: ['pull', 'vertical'] },
  { name: 'double_under', name_pt: 'Double Under', modality: 'crossfit', primary_muscles: ['calves'], secondary_muscles: ['shoulders', 'core'], equipment: ['jump_rope'], movement_type: 'skill', difficulty: 'intermediate', video_url: '', execution_tips: 'Pulsos relaxados, giro rápido. Pulo mais alto que single under. Olhe para frente.', tags: ['cardio'] },
  { name: 'rowing', name_pt: 'Remo Ergômetro', modality: 'crossfit', primary_muscles: ['back', 'hamstrings'], secondary_muscles: ['quadriceps', 'biceps', 'core'], equipment: ['rower'], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Pernas-costas-braços na puxada. Braços-costas-pernas na volta. Ritmo respiratório.', tags: ['pull', 'cardio'] },
  { name: 'assault_bike', name_pt: 'Assault Bike', modality: 'crossfit', primary_muscles: ['quadriceps', 'hamstrings'], secondary_muscles: ['shoulders', 'core'], equipment: ['assault_bike'], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Braços e pernas trabalhando juntos. Mantenha cadência alta. Respire ritmicamente.', tags: ['cardio'] },
  { name: 'clean', name_pt: 'Clean (Arremesso)', modality: 'crossfit', primary_muscles: ['quadriceps', 'glutes', 'back'], secondary_muscles: ['hamstrings', 'traps', 'shoulders'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Primeira puxada controlada. Segunda puxada explosiva. Receba em front rack com cotovelos altos.', tags: ['hinge'] },
  { name: 'snatch', name_pt: 'Snatch (Arranco)', modality: 'crossfit', primary_muscles: ['shoulders', 'quadriceps', 'back'], secondary_muscles: ['glutes', 'traps', 'core'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Pegada larga. Puxada explosiva. Receba em overhead squat. Braços travados.', tags: ['hinge', 'push'] },
  { name: 'deadlift', name_pt: 'Levantamento Terra', modality: 'crossfit', primary_muscles: ['hamstrings', 'glutes', 'back'], secondary_muscles: ['quadriceps', 'traps', 'forearms'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Costas retas, core firme. Empurre o chão. Barra rente ao corpo. Lockout completo.', tags: ['hinge'] },
  { name: 'front_squat', name_pt: 'Front Squat', modality: 'crossfit', primary_muscles: ['quadriceps'], secondary_muscles: ['glutes', 'core'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Cotovelos altos em front rack. Tronco ereto. Profundidade total.', tags: ['squat'] },
  { name: 'overhead_squat', name_pt: 'Overhead Squat', modality: 'crossfit', primary_muscles: ['quadriceps', 'shoulders'], secondary_muscles: ['core', 'glutes'], equipment: ['barbell'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Barra acima da cabeça, braços travados. Mobilidade de ombro e quadril essencial.', tags: ['squat'] },
  { name: 'kettlebell_swing', name_pt: 'Swing com Kettlebell', modality: 'crossfit', primary_muscles: ['glutes', 'hamstrings'], secondary_muscles: ['core', 'shoulders'], equipment: ['kettlebell'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Potência vem do quadril, não dos braços. Aperte o glúteo no topo. American vai acima da cabeça.', tags: ['hinge'] },
  { name: 'farmers_carry', name_pt: 'Farmer\'s Carry', modality: 'crossfit', primary_muscles: ['forearms', 'traps'], secondary_muscles: ['core', 'shoulders'], equipment: ['dumbbell', 'kettlebell'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Ombros para trás e para baixo. Core firme. Passos curtos e rápidos.', tags: ['carry'] },
  { name: 'rope_climb', name_pt: 'Escalada na Corda', modality: 'crossfit', primary_muscles: ['lats', 'biceps'], secondary_muscles: ['forearms', 'core'], equipment: ['rope'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Use a técnica de pé. Puxe com os braços enquanto empurra com as pernas.', tags: ['pull', 'vertical'] },
  { name: 'handstand_pushup', name_pt: 'Flexão em Pino', modality: 'crossfit', primary_muscles: ['shoulders'], secondary_muscles: ['triceps', 'core'], equipment: [], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Cabeça toca o chão. Kip com as pernas para ajudar. Core apertado.', tags: ['push', 'vertical'] },
  { name: 'muscle_up', name_pt: 'Muscle Up', modality: 'crossfit', primary_muscles: ['lats', 'chest'], secondary_muscles: ['biceps', 'triceps', 'core'], equipment: ['rings', 'pullup_bar'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Kip agressivo. Transição rápida. Empurre forte no dip.', tags: ['pull', 'push'] },
  { name: 'ring_dip', name_pt: 'Mergulho nas Argolas', modality: 'crossfit', primary_muscles: ['triceps', 'chest'], secondary_muscles: ['shoulders'], equipment: ['rings'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Argolas junto ao corpo. Desça controlado. Extensão completa no topo.', tags: ['push'] },
  { name: 'turkish_getup', name_pt: 'Turkish Get-Up', modality: 'crossfit', primary_muscles: ['core', 'shoulders'], secondary_muscles: ['glutes', 'quadriceps'], equipment: ['kettlebell'], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Cada etapa controlada. Olhar no kettlebell. Braço estendido durante todo o movimento.', tags: [] },
  { name: 'pistol_squat', name_pt: 'Pistol Squat', modality: 'crossfit', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['core', 'hamstrings'], equipment: [], movement_type: 'compound', difficulty: 'advanced', video_url: '', execution_tips: 'Uma perna estendida à frente. Desça controlado. Use uma caixa para escalar.', tags: ['squat'] },

  // ──────────────────────────────────────────────
  // HYROX (~15)
  // ──────────────────────────────────────────────
  { name: 'skierg', name_pt: 'SkiErg', modality: 'hyrox', primary_muscles: ['lats', 'core'], secondary_muscles: ['triceps', 'shoulders'], equipment: ['skierg'], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Puxe do alto com os braços e tronco. Flexione os joelhos levemente. Ritmo constante.', tags: ['pull', 'cardio'] },
  { name: 'sled_push', name_pt: 'Sled Push', modality: 'hyrox', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['calves', 'core', 'shoulders'], equipment: ['sled'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Braços estendidos. Corpo inclinado. Passos curtos e rápidos. Drive com as pernas.', tags: ['push'] },
  { name: 'sled_pull', name_pt: 'Sled Pull', modality: 'hyrox', primary_muscles: ['back', 'biceps'], secondary_muscles: ['forearms', 'core'], equipment: ['sled', 'rope'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Sente baixo, puxe mão sobre mão na corda. Core estabilizado.', tags: ['pull'] },
  { name: 'burpee_broad_jump', name_pt: 'Burpee Broad Jump', modality: 'hyrox', primary_muscles: ['quadriceps', 'chest'], secondary_muscles: ['glutes', 'core', 'shoulders'], equipment: [], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Burpee completo seguido de salto em distância. Aterrisse estável antes do próximo.', tags: ['push', 'squat'] },
  { name: 'sandbag_lunge', name_pt: 'Lunge com Sandbag', modality: 'hyrox', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['hamstrings', 'core'], equipment: ['sandbag'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Sandbag no ombro ou abraçado. Passos longos. Joelho traseiro quase toca o chão.', tags: ['squat'] },
  { name: 'running_intervals', name_pt: 'Corrida (Intervalos)', modality: 'hyrox', primary_muscles: ['quadriceps', 'calves'], secondary_muscles: ['hamstrings', 'core', 'glutes'], equipment: [], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Pace consistente. Não saia rápido demais. Controle a respiração.', tags: ['cardio'] },
  { name: 'box_stepover', name_pt: 'Box Step-Over', modality: 'hyrox', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['calves'], equipment: ['box'], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Suba uma perna de cada vez. Não pule — passe por cima. Ritmo constante.', tags: ['squat'] },
  { name: 'dead_ball_over_shoulder', name_pt: 'Dead Ball Over Shoulder', modality: 'hyrox', primary_muscles: ['back', 'glutes'], secondary_muscles: ['hamstrings', 'core', 'biceps'], equipment: ['dead_ball'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Levante a bola do chão com as pernas. Jogue por cima do ombro. Alterne lados.', tags: ['hinge'] },
  { name: 'battle_ropes', name_pt: 'Battle Ropes', modality: 'hyrox', primary_muscles: ['shoulders', 'core'], secondary_muscles: ['forearms', 'back'], equipment: ['battle_ropes'], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Ondas alternadas ou simultâneas. Joelhos flexionados. Amplitude total nos braços.', tags: ['cardio'] },
  { name: 'bear_crawl', name_pt: 'Bear Crawl', modality: 'hyrox', primary_muscles: ['core', 'shoulders'], secondary_muscles: ['quadriceps', 'triceps'], equipment: [], movement_type: 'compound', difficulty: 'beginner', video_url: '', execution_tips: 'Joelhos fora do chão. Movimento contralateral. Core apertado, quadril baixo.', tags: [] },
  { name: 'weighted_step_up', name_pt: 'Step-Up com Peso', modality: 'hyrox', primary_muscles: ['quadriceps', 'glutes'], secondary_muscles: ['hamstrings', 'calves'], equipment: ['dumbbell', 'box'], movement_type: 'compound', difficulty: 'intermediate', video_url: '', execution_tips: 'Pé inteiro na caixa. Empurre com a perna de cima, não impulse com a de baixo.', tags: ['squat'] },

  // ──────────────────────────────────────────────
  // SWIMMING (~10)
  // ──────────────────────────────────────────────
  { name: 'freestyle', name_pt: 'Nado Livre (Crawl)', modality: 'swimming', primary_muscles: ['lats', 'shoulders'], secondary_muscles: ['core', 'triceps'], equipment: [], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Rotação do corpo a cada braçada. Cotovelo alto na recuperação. Pernas estendidas.', tags: ['cardio', 'pull'] },
  { name: 'backstroke', name_pt: 'Nado Costas', modality: 'swimming', primary_muscles: ['lats', 'shoulders'], secondary_muscles: ['core', 'triceps'], equipment: [], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Corpo na horizontal. Braçada alternada. Rotação do quadril.', tags: ['cardio', 'pull'] },
  { name: 'breaststroke', name_pt: 'Nado Peito', modality: 'swimming', primary_muscles: ['chest', 'quadriceps'], secondary_muscles: ['shoulders', 'core'], equipment: [], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Puxe e respire, chute e deslize. Movimento coordenado de braços e pernas.', tags: ['cardio'] },
  { name: 'butterfly', name_pt: 'Nado Borboleta', modality: 'swimming', primary_muscles: ['shoulders', 'lats', 'core'], secondary_muscles: ['chest', 'triceps'], equipment: [], movement_type: 'cardio', difficulty: 'advanced', video_url: '', execution_tips: 'Ondulação do corpo inteiro. Dois chutes por braçada. Puxada simultânea.', tags: ['cardio'] },
  { name: 'swim_sprint_intervals', name_pt: 'Tiros de Velocidade', modality: 'swimming', primary_muscles: ['lats', 'shoulders', 'quadriceps'], secondary_muscles: ['core'], equipment: [], movement_type: 'cardio', difficulty: 'intermediate', video_url: '', execution_tips: 'Máxima intensidade por 25-50m. Descanse 30-60s entre tiros.', tags: ['cardio'] },
  { name: 'kick_sets', name_pt: 'Séries de Pernada', modality: 'swimming', primary_muscles: ['quadriceps', 'calves'], secondary_muscles: ['core', 'glutes'], equipment: ['kickboard'], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Prancha na frente. Pernada partindo do quadril, não do joelho. Pés relaxados.', tags: ['cardio'] },
  { name: 'pull_buoy_sets', name_pt: 'Séries com Pull Buoy', modality: 'swimming', primary_muscles: ['lats', 'shoulders'], secondary_muscles: ['triceps', 'core'], equipment: ['pull_buoy'], movement_type: 'cardio', difficulty: 'beginner', video_url: '', execution_tips: 'Boia entre as pernas. Foco na braçada e rotação do corpo. Sem pernada.', tags: ['cardio', 'pull'] },
  { name: 'swim_endurance', name_pt: 'Nado Contínuo (Endurance)', modality: 'swimming', primary_muscles: ['lats', 'shoulders'], secondary_muscles: ['core', 'quadriceps'], equipment: [], movement_type: 'cardio', difficulty: 'intermediate', video_url: '', execution_tips: 'Ritmo sustentável por 20-40 min. Respiração bilateral. Eficiência na braçada.', tags: ['cardio'] },
  { name: 'treading_water', name_pt: 'Sustentação na Água', modality: 'swimming', primary_muscles: ['core', 'shoulders'], secondary_muscles: ['quadriceps', 'calves'], equipment: [], movement_type: 'cardio', difficulty: 'intermediate', video_url: '', execution_tips: 'Pernada de peito ou tesoura. Mãos em sculling. Mantenha cabeça fora da água.', tags: ['cardio'] },
];
