/**
 * Expanded ingredients seed — ~190 NEW Brazilian foods.
 *
 * Macros are per 100 g (or 100 ml for liquids) and follow TACO
 * (Tabela Brasileira de Composição de Alimentos) values where available.
 *
 * Calorie cross-check formula:
 *   protein × 4 + carb × 4 + fat × 9 + fiber × 2  ≈  calories_per_100g
 *
 * IDs start at 111 to avoid collision with the original 110-item seed.
 */

export const EXPANDED_INGREDIENTS = [
  // ──────────────────────────────────────────────
  // PROTEINS (~15 new)
  // ──────────────────────────────────────────────
  {
    name: 'Lean ground beef',
    name_pt: 'Carne moída magra',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 21.0,
    carb_per_100g: 0.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 131,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 porção (100g)',
  },
  {
    name: 'Beef short ribs',
    name_pt: 'Costela bovina',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 18.0,
    carb_per_100g: 0.0,
    fat_per_100g: 23.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 283,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 porção (100g)',
  },
  {
    name: 'Calabresa sausage',
    name_pt: 'Linguiça calabresa',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 15.1,
    carb_per_100g: 2.2,
    fat_per_100g: 25.8,
    fiber_per_100g: 0.0,
    calories_per_100g: 303,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1 gomo (50g)',
  },
  {
    name: 'Canned sardines',
    name_pt: 'Sardinha em lata',
    category: 'protein',
    store_section: 'canned',
    protein_per_100g: 22.6,
    carb_per_100g: 0.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 192,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 84,
    default_portion_label: '1 lata drenada (84g)',
  },
  {
    name: 'Ham',
    name_pt: 'Presunto',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 14.0,
    carb_per_100g: 1.8,
    fat_per_100g: 8.6,
    fiber_per_100g: 0.0,
    calories_per_100g: 141,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 fatias (30g)',
  },
  {
    name: 'Turkey breast deli',
    name_pt: 'Peito de peru',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 17.5,
    carb_per_100g: 1.5,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 86,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 fatias (30g)',
  },
  {
    name: 'Canned tuna',
    name_pt: 'Atum em lata',
    category: 'protein',
    store_section: 'canned',
    protein_per_100g: 26.2,
    carb_per_100g: 0.0,
    fat_per_100g: 2.6,
    fiber_per_100g: 0.0,
    calories_per_100g: 130,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '1 lata drenada (60g)',
  },
  {
    name: 'Jerked beef',
    name_pt: 'Carne seca',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 53.0,
    carb_per_100g: 0.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 275,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 80,
    default_portion_label: '1 porção (80g)',
  },
  {
    name: 'Beef liver',
    name_pt: 'Fígado bovino',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 20.4,
    carb_per_100g: 3.9,
    fat_per_100g: 3.6,
    fiber_per_100g: 0.0,
    calories_per_100g: 130,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 bife (100g)',
  },
  {
    name: 'Hake',
    name_pt: 'Merluza',
    category: 'protein',
    store_section: 'frozen',
    protein_per_100g: 16.6,
    carb_per_100g: 0.0,
    fat_per_100g: 1.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 78,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 filé (120g)',
  },
  {
    name: 'Chicken hearts',
    name_pt: 'Coração de frango',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 16.5,
    carb_per_100g: 0.1,
    fat_per_100g: 9.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 153,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 espeto (100g)',
  },
  {
    name: 'Flank steak',
    name_pt: 'Fraldinha',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 21.6,
    carb_per_100g: 0.0,
    fat_per_100g: 10.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 178,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 porção (120g)',
  },
  {
    name: 'Picanha',
    name_pt: 'Picanha',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 21.0,
    carb_per_100g: 0.0,
    fat_per_100g: 14.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 212,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 fatia (120g)',
  },
  {
    name: 'Chicken drumstick',
    name_pt: 'Sobrecoxa de frango',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 17.3,
    carb_per_100g: 0.0,
    fat_per_100g: 10.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 163,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 unidade (100g)',
  },
  {
    name: 'Duck',
    name_pt: 'Pato',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 19.0,
    carb_per_100g: 0.0,
    fat_per_100g: 11.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 180,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 porção (100g)',
  },

  // ──────────────────────────────────────────────
  // VEGETABLES (~19 new)
  // ──────────────────────────────────────────────
  {
    name: 'Sweet corn',
    name_pt: 'Milho verde',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 3.2,
    carb_per_100g: 18.7,
    fat_per_100g: 1.3,
    fiber_per_100g: 2.0,
    calories_per_100g: 96,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 espiga (100g)',
  },
  {
    name: 'Fresh peas',
    name_pt: 'Ervilha fresca',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 5.4,
    carb_per_100g: 14.4,
    fat_per_100g: 0.4,
    fiber_per_100g: 5.1,
    calories_per_100g: 81,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 80,
    default_portion_label: '1/2 xícara (80g)',
  },
  {
    name: 'Okra',
    name_pt: 'Quiabo',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.9,
    carb_per_100g: 7.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.2,
    calories_per_100g: 33,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 80,
    default_portion_label: '5 unidades (80g)',
  },
  {
    name: 'Jilo',
    name_pt: 'Jiló',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.4,
    carb_per_100g: 7.0,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.8,
    calories_per_100g: 30,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '2 unidades (60g)',
  },
  {
    name: 'Collard greens',
    name_pt: 'Couve manteiga',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 2.9,
    carb_per_100g: 4.3,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.1,
    calories_per_100g: 27,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '1 xícara picada (60g)',
  },
  {
    name: 'Watercress',
    name_pt: 'Agrião',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 2.3,
    carb_per_100g: 1.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.5,
    calories_per_100g: 11,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1 maço pequeno (50g)',
  },
  {
    name: 'Heart of palm',
    name_pt: 'Palmito',
    category: 'vegetable',
    store_section: 'canned',
    protein_per_100g: 2.5,
    carb_per_100g: 2.6,
    fat_per_100g: 0.6,
    fiber_per_100g: 1.5,
    calories_per_100g: 26,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '3 rodelas (50g)',
  },
  {
    name: 'Maxixe',
    name_pt: 'Maxixe',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.0,
    carb_per_100g: 2.7,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.5,
    calories_per_100g: 13,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '4 unidades (60g)',
  },
  {
    name: 'Chicory',
    name_pt: 'Chicória',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.7,
    carb_per_100g: 4.7,
    fat_per_100g: 0.3,
    fiber_per_100g: 4.0,
    calories_per_100g: 23,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1 prato de sobremesa (50g)',
  },
  {
    name: 'Taro',
    name_pt: 'Taioba',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 2.0,
    carb_per_100g: 4.8,
    fat_per_100g: 0.7,
    fiber_per_100g: 2.8,
    calories_per_100g: 28,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1 porção (50g)',
  },
  {
    name: 'Chives',
    name_pt: 'Cebolinha',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 3.3,
    carb_per_100g: 4.4,
    fat_per_100g: 0.7,
    fiber_per_100g: 2.5,
    calories_per_100g: 30,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 10,
    default_portion_label: '1 colher de sopa (10g)',
  },
  {
    name: 'Radish',
    name_pt: 'Rabanete',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 0.7,
    carb_per_100g: 3.4,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.6,
    calories_per_100g: 16,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '3 unidades (30g)',
  },
  {
    name: 'Leek',
    name_pt: 'Alho-poró',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.5,
    carb_per_100g: 14.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.8,
    calories_per_100g: 61,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1/2 talo (50g)',
  },
  {
    name: 'Celery',
    name_pt: 'Salsão',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 0.7,
    carb_per_100g: 3.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.6,
    calories_per_100g: 14,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 40,
    default_portion_label: '1 talo (40g)',
  },
  {
    name: 'Arrowroot',
    name_pt: 'Araruta',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 0.3,
    carb_per_100g: 13.4,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.3,
    calories_per_100g: 54,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '1 porção (60g)',
  },
  {
    name: 'Sweet potato leaf',
    name_pt: 'Folha de batata doce',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 3.2,
    carb_per_100g: 5.3,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.5,
    calories_per_100g: 30,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1 porção (50g)',
  },
  {
    name: 'Scarlet eggplant',
    name_pt: 'Jiló roxo',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.2,
    carb_per_100g: 6.5,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.4,
    calories_per_100g: 28,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '2 unidades (60g)',
  },
  {
    name: 'Spring onion',
    name_pt: 'Cebola roxa',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 1.1,
    carb_per_100g: 9.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.7,
    calories_per_100g: 40,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1/2 unidade (50g)',
  },
  {
    name: 'Ora-pro-nobis',
    name_pt: 'Ora-pro-nóbis',
    category: 'vegetable',
    store_section: 'produce',
    protein_per_100g: 2.0,
    carb_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 3.8,
    calories_per_100g: 26,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '1 xícara (50g)',
  },

  // ──────────────────────────────────────────────
  // CARBS (~18 new)
  // ──────────────────────────────────────────────
  {
    name: 'French bread roll',
    name_pt: 'Pão francês',
    category: 'carb',
    store_section: 'bakery',
    protein_per_100g: 8.5,
    carb_per_100g: 58.6,
    fat_per_100g: 3.1,
    fiber_per_100g: 2.3,
    calories_per_100g: 300,
    allergen_tags: ['gluten'],
    unit: 'un',
    default_portion_g: 50,
    default_portion_label: '1 unidade (50g)',
  },
  {
    name: 'Whole wheat bread',
    name_pt: 'Pão integral',
    category: 'carb',
    store_section: 'bakery',
    protein_per_100g: 9.4,
    carb_per_100g: 44.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 6.9,
    calories_per_100g: 246,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 fatia (30g)',
  },
  {
    name: 'Cooked pasta',
    name_pt: 'Macarrão cozido',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 5.0,
    carb_per_100g: 27.9,
    fat_per_100g: 0.9,
    fiber_per_100g: 1.8,
    calories_per_100g: 141,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 150,
    default_portion_label: '1 prato raso (150g)',
  },
  {
    name: 'Corn couscous',
    name_pt: 'Cuscuz de milho',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 2.4,
    carb_per_100g: 25.0,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.2,
    calories_per_100g: 113,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 135,
    default_portion_label: '1 fatia (135g)',
  },
  {
    name: 'Farofa ready-made',
    name_pt: 'Farofa pronta',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 1.8,
    carb_per_100g: 71.6,
    fat_per_100g: 6.0,
    fiber_per_100g: 6.5,
    calories_per_100g: 365,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Cooked cassava',
    name_pt: 'Mandioca cozida',
    category: 'carb',
    store_section: 'produce',
    protein_per_100g: 0.6,
    carb_per_100g: 30.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.6,
    calories_per_100g: 125,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '2 pedaços (100g)',
  },
  {
    name: 'White potato',
    name_pt: 'Batata inglesa',
    category: 'carb',
    store_section: 'produce',
    protein_per_100g: 1.8,
    carb_per_100g: 18.5,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.3,
    calories_per_100g: 77,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 140,
    default_portion_label: '1 unidade média (140g)',
  },
  {
    name: 'Granola',
    name_pt: 'Granola',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 9.4,
    carb_per_100g: 64.0,
    fat_per_100g: 14.6,
    fiber_per_100g: 6.8,
    calories_per_100g: 421,
    allergen_tags: ['gluten', 'tree_nuts'],
    unit: 'g',
    default_portion_g: 40,
    default_portion_label: '1/4 xícara (40g)',
  },
  {
    name: 'Breakfast cereal',
    name_pt: 'Cereal matinal',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 7.0,
    carb_per_100g: 81.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 3.0,
    calories_per_100g: 368,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1/2 xícara (30g)',
  },
  {
    name: 'Whole wheat toast',
    name_pt: 'Torrada integral',
    category: 'carb',
    store_section: 'bakery',
    protein_per_100g: 11.3,
    carb_per_100g: 63.5,
    fat_per_100g: 5.9,
    fiber_per_100g: 7.4,
    calories_per_100g: 359,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '2 torradas (15g)',
  },
  {
    name: 'Polenta',
    name_pt: 'Polenta',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 1.4,
    carb_per_100g: 16.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.7,
    calories_per_100g: 70,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 fatia (100g)',
  },
  {
    name: 'Canjica (hominy)',
    name_pt: 'Canjica',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 1.6,
    carb_per_100g: 17.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.8,
    calories_per_100g: 78,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 150,
    default_portion_label: '1 concha (150g)',
  },
  {
    name: 'Popcorn kernels',
    name_pt: 'Milho de pipoca',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 9.4,
    carb_per_100g: 74.3,
    fat_per_100g: 4.7,
    fiber_per_100g: 14.5,
    calories_per_100g: 375,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Cooked pinto beans',
    name_pt: 'Feijão carioca cozido',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 5.1,
    carb_per_100g: 13.6,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.5,
    calories_per_100g: 77,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 86,
    default_portion_label: '1 concha (86g)',
  },
  {
    name: 'Cooked black beans',
    name_pt: 'Feijão preto cozido',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 4.5,
    carb_per_100g: 14.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.4,
    calories_per_100g: 77,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 86,
    default_portion_label: '1 concha (86g)',
  },
  {
    name: 'Cooked lentils',
    name_pt: 'Lentilha cozida',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 9.0,
    carb_per_100g: 20.1,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.9,
    calories_per_100g: 116,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '3 colheres de sopa (100g)',
  },
  {
    name: 'Cooked chickpeas',
    name_pt: 'Grão de bico cozido',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 8.9,
    carb_per_100g: 27.4,
    fat_per_100g: 2.6,
    fiber_per_100g: 7.6,
    calories_per_100g: 164,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '3 colheres de sopa (100g)',
  },
  {
    name: 'Cooked dried peas',
    name_pt: 'Ervilha seca cozida',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 8.3,
    carb_per_100g: 21.1,
    fat_per_100g: 0.4,
    fiber_per_100g: 8.3,
    calories_per_100g: 118,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '3 colheres de sopa (100g)',
  },

  // ──────────────────────────────────────────────
  // FATS (~7 new)
  // ──────────────────────────────────────────────
  {
    name: 'Heavy cream',
    name_pt: 'Creme de leite',
    category: 'fat',
    store_section: 'dairy',
    protein_per_100g: 2.1,
    carb_per_100g: 3.4,
    fat_per_100g: 20.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 202,
    allergen_tags: ['dairy'],
    unit: 'ml',
    default_portion_g: 25,
    default_portion_label: '1 colher de sopa (25g)',
  },
  {
    name: 'Requeijao',
    name_pt: 'Requeijão',
    category: 'fat',
    store_section: 'dairy',
    protein_per_100g: 7.5,
    carb_per_100g: 3.0,
    fat_per_100g: 22.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 240,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 colher de sopa (30g)',
  },
  {
    name: 'Mayonnaise',
    name_pt: 'Maionese',
    category: 'fat',
    store_section: 'condiments',
    protein_per_100g: 1.1,
    carb_per_100g: 2.7,
    fat_per_100g: 75.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 691,
    allergen_tags: ['egg', 'soy'],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Margarine',
    name_pt: 'Margarina',
    category: 'fat',
    store_section: 'dairy',
    protein_per_100g: 0.2,
    carb_per_100g: 0.4,
    fat_per_100g: 80.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 720,
    allergen_tags: ['soy'],
    unit: 'g',
    default_portion_g: 10,
    default_portion_label: '1 colher de chá (10g)',
  },
  {
    name: 'Dark chocolate 70%',
    name_pt: 'Chocolate amargo 70%',
    category: 'fat',
    store_section: 'snacks',
    protein_per_100g: 7.8,
    carb_per_100g: 33.0,
    fat_per_100g: 42.6,
    fiber_per_100g: 10.9,
    calories_per_100g: 545,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 25,
    default_portion_label: '1 quadrado (25g)',
  },
  {
    name: 'Peanut butter',
    name_pt: 'Pasta de amendoim',
    category: 'fat',
    store_section: 'grains',
    protein_per_100g: 27.0,
    carb_per_100g: 17.6,
    fat_per_100g: 50.4,
    fiber_per_100g: 6.0,
    calories_per_100g: 632,
    allergen_tags: ['peanuts'],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Coconut milk (canned)',
    name_pt: 'Leite de coco (culinário)',
    category: 'fat',
    store_section: 'canned',
    protein_per_100g: 2.0,
    carb_per_100g: 2.8,
    fat_per_100g: 21.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 210,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 65,
    default_portion_label: '1/3 caixinha (65ml)',
  },

  // ──────────────────────────────────────────────
  // DAIRY & ALTERNATIVES (~9 new)
  // ──────────────────────────────────────────────
  {
    name: 'Whole milk',
    name_pt: 'Leite integral',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 3.2,
    carb_per_100g: 4.7,
    fat_per_100g: 3.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 61,
    allergen_tags: ['dairy'],
    unit: 'ml',
    default_portion_g: 200,
    default_portion_label: '1 copo (200ml)',
  },
  {
    name: 'Skim milk',
    name_pt: 'Leite desnatado',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 3.4,
    carb_per_100g: 5.0,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.0,
    calories_per_100g: 35,
    allergen_tags: ['dairy'],
    unit: 'ml',
    default_portion_g: 200,
    default_portion_label: '1 copo (200ml)',
  },
  {
    name: 'Mozzarella cheese',
    name_pt: 'Queijo mussarela',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 22.6,
    carb_per_100g: 2.2,
    fat_per_100g: 22.4,
    fiber_per_100g: 0.0,
    calories_per_100g: 300,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 fatia (30g)',
  },
  {
    name: 'Cottage cheese',
    name_pt: 'Queijo cottage',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 11.1,
    carb_per_100g: 3.4,
    fat_per_100g: 4.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 98,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 50,
    default_portion_label: '2 colheres de sopa (50g)',
  },
  {
    name: 'Ricotta cheese',
    name_pt: 'Ricota',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 11.4,
    carb_per_100g: 3.0,
    fat_per_100g: 13.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 174,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 fatia (30g)',
  },
  {
    name: 'Cream cheese',
    name_pt: 'Cream cheese',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 5.9,
    carb_per_100g: 4.1,
    fat_per_100g: 34.9,
    fiber_per_100g: 0.0,
    calories_per_100g: 350,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 colher de sopa (30g)',
  },
  {
    name: 'Condensed milk',
    name_pt: 'Leite condensado',
    category: 'dairy_alt',
    store_section: 'canned',
    protein_per_100g: 7.5,
    carb_per_100g: 55.5,
    fat_per_100g: 8.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 328,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 20,
    default_portion_label: '1 colher de sopa (20g)',
  },
  {
    name: 'Greek yogurt',
    name_pt: 'Iogurte grego',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 10.0,
    carb_per_100g: 3.6,
    fat_per_100g: 5.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 100,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 170,
    default_portion_label: '1 pote (170g)',
  },
  {
    name: 'Prato cheese',
    name_pt: 'Queijo prato',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 22.7,
    carb_per_100g: 1.9,
    fat_per_100g: 25.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 326,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 fatia (30g)',
  },

  // ──────────────────────────────────────────────
  // FRUITS (~12 new)
  // ──────────────────────────────────────────────
  {
    name: 'Grape',
    name_pt: 'Uva',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.7,
    carb_per_100g: 16.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.9,
    calories_per_100g: 69,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 cacho pequeno (100g)',
  },
  {
    name: 'Melon',
    name_pt: 'Melão',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.8,
    carb_per_100g: 8.2,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.9,
    calories_per_100g: 36,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 150,
    default_portion_label: '1 fatia (150g)',
  },
  {
    name: 'Pear',
    name_pt: 'Pera',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.4,
    carb_per_100g: 15.2,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.1,
    calories_per_100g: 57,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 133,
    default_portion_label: '1 unidade (133g)',
  },
  {
    name: 'Plum',
    name_pt: 'Ameixa',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.7,
    carb_per_100g: 11.4,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.4,
    calories_per_100g: 46,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 70,
    default_portion_label: '1 unidade (70g)',
  },
  {
    name: 'Fresh coconut',
    name_pt: 'Coco fresco',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 3.3,
    carb_per_100g: 15.2,
    fat_per_100g: 33.5,
    fiber_per_100g: 9.0,
    calories_per_100g: 354,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 40,
    default_portion_label: '1 pedaço (40g)',
  },
  {
    name: 'Tangerine',
    name_pt: 'Tangerina',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.8,
    carb_per_100g: 13.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.8,
    calories_per_100g: 53,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 100,
    default_portion_label: '1 unidade (100g)',
  },
  {
    name: 'Cherry',
    name_pt: 'Cereja',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 1.1,
    carb_per_100g: 16.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.1,
    calories_per_100g: 63,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 80,
    default_portion_label: '10 unidades (80g)',
  },
  {
    name: 'Guava paste',
    name_pt: 'Goiabada',
    category: 'fruit',
    store_section: 'snacks',
    protein_per_100g: 0.4,
    carb_per_100g: 77.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 4.6,
    calories_per_100g: 303,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 fatia (30g)',
  },
  {
    name: 'Acerola',
    name_pt: 'Acerola',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.4,
    carb_per_100g: 7.7,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.1,
    calories_per_100g: 33,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 75,
    default_portion_label: '8 unidades (75g)',
  },
  {
    name: 'Jabuticaba',
    name_pt: 'Jabuticaba',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.6,
    carb_per_100g: 15.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.8,
    calories_per_100g: 58,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '15 unidades (100g)',
  },
  {
    name: 'Cashew fruit',
    name_pt: 'Caju',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 1.0,
    carb_per_100g: 10.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.5,
    calories_per_100g: 43,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 120,
    default_portion_label: '1 unidade (120g)',
  },
  {
    name: 'Apple',
    name_pt: 'Maçã',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.3,
    carb_per_100g: 13.8,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
    calories_per_100g: 52,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 150,
    default_portion_label: '1 unidade (150g)',
  },

  // ──────────────────────────────────────────────
  // SEASONINGS & CONDIMENTS (~5 new)
  // ──────────────────────────────────────────────
  {
    name: 'Soy sauce (shoyu)',
    name_pt: 'Molho de soja (shoyu)',
    category: 'seasoning',
    store_section: 'condiments',
    protein_per_100g: 5.6,
    carb_per_100g: 5.6,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.8,
    calories_per_100g: 53,
    allergen_tags: ['soy', 'gluten'],
    unit: 'ml',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15ml)',
  },
  {
    name: 'Ketchup',
    name_pt: 'Ketchup',
    category: 'seasoning',
    store_section: 'condiments',
    protein_per_100g: 1.7,
    carb_per_100g: 27.4,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.3,
    calories_per_100g: 112,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Mustard',
    name_pt: 'Mostarda',
    category: 'seasoning',
    store_section: 'condiments',
    protein_per_100g: 4.4,
    carb_per_100g: 5.3,
    fat_per_100g: 4.0,
    fiber_per_100g: 3.3,
    calories_per_100g: 60,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 10,
    default_portion_label: '1 colher de chá (10g)',
  },
  {
    name: 'Refined sugar',
    name_pt: 'Açúcar refinado',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 0.0,
    carb_per_100g: 99.5,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 398,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5g)',
  },
  {
    name: 'Honey',
    name_pt: 'Mel',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 0.3,
    carb_per_100g: 82.4,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.2,
    calories_per_100g: 304,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 21,
    default_portion_label: '1 colher de sopa (21g)',
  },

  // ──────────────────────────────────────────────
  // PREPARED FOODS (~15 new)
  // ──────────────────────────────────────────────
  {
    name: 'Cooked white rice',
    name_pt: 'Arroz branco cozido',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 2.5,
    carb_per_100g: 28.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1.6,
    calories_per_100g: 128,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '3 colheres de sopa (100g)',
  },
  {
    name: 'Feijao tropeiro',
    name_pt: 'Feijão tropeiro',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 9.5,
    carb_per_100g: 20.6,
    fat_per_100g: 7.1,
    fiber_per_100g: 5.0,
    calories_per_100g: 185,
    allergen_tags: ['egg'],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '2 colheres de servir (120g)',
  },
  {
    name: 'Vegetable soup',
    name_pt: 'Sopa de legumes',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 1.5,
    carb_per_100g: 5.8,
    fat_per_100g: 1.0,
    fiber_per_100g: 1.2,
    calories_per_100g: 38,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 300,
    default_portion_label: '1 prato fundo (300ml)',
  },
  {
    name: 'Fresh orange juice',
    name_pt: 'Suco de laranja natural',
    category: 'prepared',
    store_section: 'beverages',
    protein_per_100g: 0.8,
    carb_per_100g: 10.4,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.2,
    calories_per_100g: 45,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 250,
    default_portion_label: '1 copo (250ml)',
  },
  {
    name: 'Pure acai',
    name_pt: 'Açaí puro',
    category: 'prepared',
    store_section: 'frozen',
    protein_per_100g: 3.8,
    carb_per_100g: 6.2,
    fat_per_100g: 12.2,
    fiber_per_100g: 2.6,
    calories_per_100g: 150,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 200,
    default_portion_label: '1 tigela (200g)',
  },
  {
    name: 'Ready tapioca',
    name_pt: 'Tapioca pronta',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 0.5,
    carb_per_100g: 22.0,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.3,
    calories_per_100g: 88,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 80,
    default_portion_label: '1 unidade (80g)',
  },
  {
    name: 'Pao de queijo',
    name_pt: 'Pão de queijo',
    category: 'prepared',
    store_section: 'bakery',
    protein_per_100g: 5.6,
    carb_per_100g: 34.2,
    fat_per_100g: 14.3,
    fiber_per_100g: 0.5,
    calories_per_100g: 290,
    allergen_tags: ['dairy', 'egg'],
    unit: 'un',
    default_portion_g: 25,
    default_portion_label: '1 unidade média (25g)',
  },
  {
    name: 'Coxinha',
    name_pt: 'Coxinha',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 8.7,
    carb_per_100g: 24.5,
    fat_per_100g: 14.0,
    fiber_per_100g: 0.6,
    calories_per_100g: 259,
    allergen_tags: ['gluten', 'egg'],
    unit: 'un',
    default_portion_g: 80,
    default_portion_label: '1 unidade (80g)',
  },
  {
    name: 'Meat pastel',
    name_pt: 'Pastel de carne',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 8.5,
    carb_per_100g: 25.6,
    fat_per_100g: 17.2,
    fiber_per_100g: 0.8,
    calories_per_100g: 292,
    allergen_tags: ['gluten', 'egg'],
    unit: 'un',
    default_portion_g: 100,
    default_portion_label: '1 unidade (100g)',
  },
  {
    name: 'Empada',
    name_pt: 'Empada',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 7.2,
    carb_per_100g: 26.0,
    fat_per_100g: 18.5,
    fiber_per_100g: 0.7,
    calories_per_100g: 297,
    allergen_tags: ['gluten', 'dairy', 'egg'],
    unit: 'un',
    default_portion_g: 45,
    default_portion_label: '1 unidade (45g)',
  },
  {
    name: 'Brigadeiro',
    name_pt: 'Brigadeiro',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 5.8,
    carb_per_100g: 60.0,
    fat_per_100g: 10.5,
    fiber_per_100g: 1.5,
    calories_per_100g: 358,
    allergen_tags: ['dairy'],
    unit: 'un',
    default_portion_g: 20,
    default_portion_label: '1 unidade (20g)',
  },
  {
    name: 'Milk pudding',
    name_pt: 'Pudim de leite',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 5.0,
    carb_per_100g: 38.0,
    fat_per_100g: 6.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 231,
    allergen_tags: ['dairy', 'egg'],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 fatia (100g)',
  },
  {
    name: 'Simple cake',
    name_pt: 'Bolo simples',
    category: 'prepared',
    store_section: 'bakery',
    protein_per_100g: 5.5,
    carb_per_100g: 52.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 0.8,
    calories_per_100g: 338,
    allergen_tags: ['gluten', 'dairy', 'egg'],
    unit: 'g',
    default_portion_g: 60,
    default_portion_label: '1 fatia (60g)',
  },
  {
    name: 'Pamonha',
    name_pt: 'Pamonha',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 3.2,
    carb_per_100g: 28.5,
    fat_per_100g: 4.0,
    fiber_per_100g: 1.5,
    calories_per_100g: 164,
    allergen_tags: ['dairy'],
    unit: 'un',
    default_portion_g: 150,
    default_portion_label: '1 unidade (150g)',
  },
  {
    name: 'Sugarcane juice',
    name_pt: 'Caldo de cana',
    category: 'prepared',
    store_section: 'beverages',
    protein_per_100g: 0.2,
    carb_per_100g: 18.2,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 74,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 300,
    default_portion_label: '1 copo (300ml)',
  },

  // ──────────────────────────────────────────────
  // SUPPLEMENTS (~10 new)
  // ──────────────────────────────────────────────
  {
    name: 'Creatine monohydrate',
    name_pt: 'Creatina monohidratada',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 0.0,
    carb_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 0,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher dosadora (5g)',
  },
  {
    name: 'BCAA',
    name_pt: 'BCAA',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 95.0,
    carb_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 380,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 dose (5g)',
  },
  {
    name: 'Glutamine',
    name_pt: 'Glutamina',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 100.0,
    carb_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 400,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 dose (5g)',
  },
  {
    name: 'Casein protein',
    name_pt: 'Caseína',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 80.0,
    carb_per_100g: 4.0,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 350,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 scoop (30g)',
  },
  {
    name: 'Egg albumin powder',
    name_pt: 'Albumina em pó',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 82.0,
    carb_per_100g: 4.5,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 350,
    allergen_tags: ['egg'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Maltodextrin',
    name_pt: 'Maltodextrina',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 0.0,
    carb_per_100g: 95.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 380,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Dextrose',
    name_pt: 'Dextrose',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 0.0,
    carb_per_100g: 100.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 400,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Omega 3 capsule',
    name_pt: 'Ômega 3 (cápsula)',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 0.0,
    carb_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 900,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 1,
    default_portion_label: '1 cápsula (1g)',
  },
  {
    name: 'Vitamin C tablet',
    name_pt: 'Vitamina C (comprimido)',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 0.0,
    carb_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 0,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 2,
    default_portion_label: '1 comprimido (2g)',
  },
  {
    name: 'Collagen powder',
    name_pt: 'Colágeno em pó',
    category: 'supplement',
    store_section: 'supplements',
    protein_per_100g: 90.0,
    carb_per_100g: 0.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 360,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 10,
    default_portion_label: '1 colher de sopa (10g)',
  },

  // ──────────────────────────────────────────────
  // SNACKS (~10 new)
  // ──────────────────────────────────────────────
  {
    name: 'Protein bar',
    name_pt: 'Barra de proteína',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 30.0,
    carb_per_100g: 35.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 5.0,
    calories_per_100g: 370,
    allergen_tags: ['dairy', 'soy'],
    unit: 'un',
    default_portion_g: 40,
    default_portion_label: '1 unidade (40g)',
  },
  {
    name: 'Rice crackers',
    name_pt: 'Biscoito de arroz',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 7.5,
    carb_per_100g: 81.0,
    fat_per_100g: 2.5,
    fiber_per_100g: 2.3,
    calories_per_100g: 382,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 25,
    default_portion_label: '4 unidades (25g)',
  },
  {
    name: 'Popped popcorn',
    name_pt: 'Pipoca estourada',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 11.0,
    carb_per_100g: 58.1,
    fat_per_100g: 15.0,
    fiber_per_100g: 13.5,
    calories_per_100g: 387,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 25,
    default_portion_label: '1 xícara (25g)',
  },
  {
    name: 'Cashew nuts',
    name_pt: 'Castanha de caju',
    category: 'snack',
    store_section: 'nuts',
    protein_per_100g: 18.2,
    carb_per_100g: 30.2,
    fat_per_100g: 43.9,
    fiber_per_100g: 3.3,
    calories_per_100g: 570,
    allergen_tags: ['tree_nuts'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 punhado (30g)',
  },
  {
    name: 'Roasted peanuts',
    name_pt: 'Amendoim torrado',
    category: 'snack',
    store_section: 'nuts',
    protein_per_100g: 26.2,
    carb_per_100g: 15.8,
    fat_per_100g: 44.0,
    fiber_per_100g: 8.0,
    calories_per_100g: 567,
    allergen_tags: ['peanuts'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 punhado (30g)',
  },
  {
    name: 'Mixed nuts',
    name_pt: 'Mix de nuts',
    category: 'snack',
    store_section: 'nuts',
    protein_per_100g: 17.0,
    carb_per_100g: 22.0,
    fat_per_100g: 50.0,
    fiber_per_100g: 5.5,
    calories_per_100g: 607,
    allergen_tags: ['tree_nuts', 'peanuts'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 punhado (30g)',
  },
  {
    name: 'Banana chips',
    name_pt: 'Banana chips',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 2.3,
    carb_per_100g: 58.4,
    fat_per_100g: 25.0,
    fiber_per_100g: 7.7,
    calories_per_100g: 465,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 porção (30g)',
  },
  {
    name: 'Cereal bar',
    name_pt: 'Barra de cereal',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 5.0,
    carb_per_100g: 72.0,
    fat_per_100g: 8.0,
    fiber_per_100g: 3.5,
    calories_per_100g: 381,
    allergen_tags: ['gluten'],
    unit: 'un',
    default_portion_g: 25,
    default_portion_label: '1 unidade (25g)',
  },
  {
    name: 'Pork rinds',
    name_pt: 'Torresmo',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 50.0,
    carb_per_100g: 0.0,
    fat_per_100g: 31.3,
    fiber_per_100g: 0.0,
    calories_per_100g: 481,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 porção (30g)',
  },
  {
    name: 'Roasted almonds',
    name_pt: 'Amêndoas torradas',
    category: 'snack',
    store_section: 'nuts',
    protein_per_100g: 21.2,
    carb_per_100g: 19.5,
    fat_per_100g: 52.5,
    fiber_per_100g: 12.5,
    calories_per_100g: 598,
    allergen_tags: ['tree_nuts'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 punhado (30g)',
  },

  // ──────────────────────────────────────────────
  // EXTRA BRAZILIAN STAPLES (~20 more to reach ~190)
  // ──────────────────────────────────────────────
  {
    name: 'Cassava flour',
    name_pt: 'Farinha de mandioca',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 1.6,
    carb_per_100g: 82.5,
    fat_per_100g: 0.5,
    fiber_per_100g: 6.5,
    calories_per_100g: 340,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Cornmeal',
    name_pt: 'Fubá de milho',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 7.2,
    carb_per_100g: 78.9,
    fat_per_100g: 1.5,
    fiber_per_100g: 4.4,
    calories_per_100g: 361,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '3 colheres de sopa (30g)',
  },
  {
    name: 'Sour starch (polvilho azedo)',
    name_pt: 'Polvilho azedo',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 0.5,
    carb_per_100g: 87.1,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.5,
    calories_per_100g: 351,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Brown sugar',
    name_pt: 'Açúcar mascavo',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 0.5,
    carb_per_100g: 95.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 377,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5g)',
  },
  {
    name: 'Coconut sugar',
    name_pt: 'Açúcar de coco',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 1.0,
    carb_per_100g: 92.0,
    fat_per_100g: 0.5,
    fiber_per_100g: 0.3,
    calories_per_100g: 375,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5g)',
  },
  {
    name: 'Demerara sugar',
    name_pt: 'Açúcar demerara',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 0.2,
    carb_per_100g: 97.5,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 389,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5g)',
  },
  {
    name: 'Whole wheat flour',
    name_pt: 'Farinha de trigo integral',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 13.2,
    carb_per_100g: 61.5,
    fat_per_100g: 2.5,
    fiber_per_100g: 10.7,
    calories_per_100g: 340,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'White flour',
    name_pt: 'Farinha de trigo',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 9.8,
    carb_per_100g: 75.1,
    fat_per_100g: 1.4,
    fiber_per_100g: 2.3,
    calories_per_100g: 361,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Sunflower oil',
    name_pt: 'Óleo de girassol',
    category: 'fat',
    store_section: 'oils',
    protein_per_100g: 0.0,
    carb_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 884,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 8,
    default_portion_label: '1 colher de sopa (8ml)',
  },
  {
    name: 'Soybean oil',
    name_pt: 'Óleo de soja',
    category: 'fat',
    store_section: 'oils',
    protein_per_100g: 0.0,
    carb_per_100g: 0.0,
    fat_per_100g: 100.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 884,
    allergen_tags: ['soy'],
    unit: 'ml',
    default_portion_g: 8,
    default_portion_label: '1 colher de sopa (8ml)',
  },
  {
    name: 'Natural yogurt',
    name_pt: 'Iogurte natural',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 4.1,
    carb_per_100g: 5.5,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 65,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 170,
    default_portion_label: '1 pote (170g)',
  },
  {
    name: 'Skimmed yogurt',
    name_pt: 'Iogurte desnatado',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 4.4,
    carb_per_100g: 6.0,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 42,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 170,
    default_portion_label: '1 pote (170g)',
  },
  {
    name: 'Parmesan cheese',
    name_pt: 'Queijo parmesão',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 35.8,
    carb_per_100g: 3.2,
    fat_per_100g: 25.8,
    fiber_per_100g: 0.0,
    calories_per_100g: 392,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 10,
    default_portion_label: '1 colher de sopa ralado (10g)',
  },
  {
    name: 'Minas cheese (fresh)',
    name_pt: 'Queijo minas frescal',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 17.4,
    carb_per_100g: 3.2,
    fat_per_100g: 20.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 264,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '1 fatia (30g)',
  },
  {
    name: 'Cupuacu',
    name_pt: 'Cupuaçu',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 1.7,
    carb_per_100g: 10.4,
    fat_per_100g: 1.2,
    fiber_per_100g: 2.0,
    calories_per_100g: 49,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 polpa (100g)',
  },
  {
    name: 'Persimmon',
    name_pt: 'Caqui',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.6,
    carb_per_100g: 19.3,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.6,
    calories_per_100g: 71,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 100,
    default_portion_label: '1 unidade (100g)',
  },
  {
    name: 'Graviola (soursop)',
    name_pt: 'Graviola',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 1.0,
    carb_per_100g: 16.8,
    fat_per_100g: 0.3,
    fiber_per_100g: 3.3,
    calories_per_100g: 66,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 fatia (100g)',
  },
  {
    name: 'Feijoada',
    name_pt: 'Feijoada',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 8.8,
    carb_per_100g: 7.9,
    fat_per_100g: 7.5,
    fiber_per_100g: 3.2,
    calories_per_100g: 134,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 200,
    default_portion_label: '1 concha cheia (200g)',
  },
  {
    name: 'Strogonoff (chicken)',
    name_pt: 'Estrogonofe de frango',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 12.0,
    carb_per_100g: 5.5,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.4,
    calories_per_100g: 143,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 150,
    default_portion_label: '1 porção (150g)',
  },
  {
    name: 'Vinagrette salsa',
    name_pt: 'Vinagrete',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 0.8,
    carb_per_100g: 4.5,
    fat_per_100g: 3.0,
    fiber_per_100g: 0.8,
    calories_per_100g: 47,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 colheres de sopa (30g)',
  },
  {
    name: 'Baiao de dois',
    name_pt: 'Baião de dois',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 6.5,
    carb_per_100g: 18.0,
    fat_per_100g: 5.0,
    fiber_per_100g: 2.5,
    calories_per_100g: 143,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 150,
    default_portion_label: '3 colheres de sopa (150g)',
  },
  {
    name: 'Acaraje',
    name_pt: 'Acarajé',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 7.0,
    carb_per_100g: 14.0,
    fat_per_100g: 18.0,
    fiber_per_100g: 2.5,
    calories_per_100g: 248,
    allergen_tags: ['shellfish'],
    unit: 'un',
    default_portion_g: 120,
    default_portion_label: '1 unidade (120g)',
  },
  {
    name: 'Esfiha (meat)',
    name_pt: 'Esfiha de carne',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 9.5,
    carb_per_100g: 30.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 1.5,
    calories_per_100g: 248,
    allergen_tags: ['gluten'],
    unit: 'un',
    default_portion_g: 60,
    default_portion_label: '1 unidade (60g)',
  },
  {
    name: 'Kibbeh (fried)',
    name_pt: 'Quibe frito',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 12.0,
    carb_per_100g: 19.0,
    fat_per_100g: 14.0,
    fiber_per_100g: 2.0,
    calories_per_100g: 250,
    allergen_tags: ['gluten'],
    unit: 'un',
    default_portion_g: 50,
    default_portion_label: '1 unidade (50g)',
  },
  {
    name: 'Peanut pacoca',
    name_pt: 'Paçoca de amendoim',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 16.5,
    carb_per_100g: 52.0,
    fat_per_100g: 19.0,
    fiber_per_100g: 3.0,
    calories_per_100g: 440,
    allergen_tags: ['peanuts'],
    unit: 'un',
    default_portion_g: 20,
    default_portion_label: '1 unidade (20g)',
  },
  {
    name: 'Dried banana',
    name_pt: 'Banana passa',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 3.5,
    carb_per_100g: 65.3,
    fat_per_100g: 0.6,
    fiber_per_100g: 5.4,
    calories_per_100g: 271,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 unidades (30g)',
  },
  {
    name: 'Corn on the cob (cooked)',
    name_pt: 'Milho verde cozido (espiga)',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 3.6,
    carb_per_100g: 19.0,
    fat_per_100g: 1.4,
    fiber_per_100g: 2.7,
    calories_per_100g: 96,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 150,
    default_portion_label: '1 espiga (150g)',
  },
  // ──────────────────────────────────────────────
  // ADDITIONAL PROTEINS (~8)
  // ──────────────────────────────────────────────
  {
    name: 'Rump steak',
    name_pt: 'Maminha',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 21.4,
    carb_per_100g: 0.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 165,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 porção (120g)',
  },
  {
    name: 'Skirt steak',
    name_pt: 'Contrafilé',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 22.0,
    carb_per_100g: 0.0,
    fat_per_100g: 11.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 191,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 bife (120g)',
  },
  {
    name: 'Chicken wing',
    name_pt: 'Asa de frango',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 18.3,
    carb_per_100g: 0.0,
    fat_per_100g: 15.1,
    fiber_per_100g: 0.0,
    calories_per_100g: 211,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 80,
    default_portion_label: '2 unidades (80g)',
  },
  {
    name: 'Beef tongue',
    name_pt: 'Língua bovina',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 16.1,
    carb_per_100g: 0.0,
    fat_per_100g: 16.2,
    fiber_per_100g: 0.0,
    calories_per_100g: 213,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 porção (100g)',
  },
  {
    name: 'Beef tripe',
    name_pt: 'Dobradinha (bucho)',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 12.1,
    carb_per_100g: 0.0,
    fat_per_100g: 3.4,
    fiber_per_100g: 0.0,
    calories_per_100g: 85,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 porção (100g)',
  },
  {
    name: 'Lamb leg',
    name_pt: 'Pernil de cordeiro',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 20.0,
    carb_per_100g: 0.0,
    fat_per_100g: 14.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 206,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '1 fatia (100g)',
  },
  {
    name: 'Tucunare (peacock bass)',
    name_pt: 'Tucunaré',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 19.8,
    carb_per_100g: 0.0,
    fat_per_100g: 1.6,
    fiber_per_100g: 0.0,
    calories_per_100g: 95,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 filé (120g)',
  },
  {
    name: 'Tambaqui',
    name_pt: 'Tambaqui',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 19.5,
    carb_per_100g: 0.0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 128,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '1 posta (120g)',
  },

  // ──────────────────────────────────────────────
  // ADDITIONAL FRUITS (~5)
  // ──────────────────────────────────────────────
  {
    name: 'Pitaya (dragon fruit)',
    name_pt: 'Pitaya',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 1.2,
    carb_per_100g: 11.0,
    fat_per_100g: 0.4,
    fiber_per_100g: 1.9,
    calories_per_100g: 50,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 150,
    default_portion_label: '1/2 unidade (150g)',
  },
  {
    name: 'Pequi',
    name_pt: 'Pequi',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 2.6,
    carb_per_100g: 13.0,
    fat_per_100g: 20.0,
    fiber_per_100g: 10.0,
    calories_per_100g: 240,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 40,
    default_portion_label: '2 caroços (40g)',
  },
  {
    name: 'Lychee',
    name_pt: 'Lichia',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.8,
    carb_per_100g: 16.5,
    fat_per_100g: 0.4,
    fiber_per_100g: 1.3,
    calories_per_100g: 66,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 80,
    default_portion_label: '6 unidades (80g)',
  },
  {
    name: 'Fig',
    name_pt: 'Figo',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.8,
    carb_per_100g: 19.2,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.9,
    calories_per_100g: 74,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 50,
    default_portion_label: '1 unidade (50g)',
  },
  {
    name: 'Umbu',
    name_pt: 'Umbu',
    category: 'fruit',
    store_section: 'produce',
    protein_per_100g: 0.8,
    carb_per_100g: 9.4,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.0,
    calories_per_100g: 37,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 30,
    default_portion_label: '1 unidade (30g)',
  },

  // ──────────────────────────────────────────────
  // ADDITIONAL PREPARED / BEVERAGES (~12)
  // ──────────────────────────────────────────────
  {
    name: 'Moqueca (fish stew)',
    name_pt: 'Moqueca',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 10.5,
    carb_per_100g: 3.5,
    fat_per_100g: 8.0,
    fiber_per_100g: 0.6,
    calories_per_100g: 131,
    allergen_tags: ['fish'],
    unit: 'g',
    default_portion_g: 200,
    default_portion_label: '1 porção (200g)',
  },
  {
    name: 'Vatapa',
    name_pt: 'Vatapá',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 5.0,
    carb_per_100g: 12.0,
    fat_per_100g: 13.0,
    fiber_per_100g: 1.5,
    calories_per_100g: 190,
    allergen_tags: ['peanuts', 'shellfish'],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '2 colheres de sopa (100g)',
  },
  {
    name: 'Tutu de feijao',
    name_pt: 'Tutu de feijão',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 6.0,
    carb_per_100g: 16.0,
    fat_per_100g: 3.5,
    fiber_per_100g: 4.0,
    calories_per_100g: 118,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 120,
    default_portion_label: '2 colheres de servir (120g)',
  },
  {
    name: 'Bolinho de bacalhau',
    name_pt: 'Bolinho de bacalhau',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 10.0,
    carb_per_100g: 20.0,
    fat_per_100g: 13.0,
    fiber_per_100g: 0.8,
    calories_per_100g: 238,
    allergen_tags: ['fish', 'gluten', 'egg'],
    unit: 'un',
    default_portion_g: 30,
    default_portion_label: '1 unidade (30g)',
  },
  {
    name: 'Risotto',
    name_pt: 'Risoto',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 3.5,
    carb_per_100g: 19.0,
    fat_per_100g: 4.5,
    fiber_per_100g: 0.5,
    calories_per_100g: 130,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 200,
    default_portion_label: '1 prato (200g)',
  },
  {
    name: 'Fried egg',
    name_pt: 'Ovo frito',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 13.6,
    carb_per_100g: 0.8,
    fat_per_100g: 14.8,
    fiber_per_100g: 0.0,
    calories_per_100g: 196,
    allergen_tags: ['egg'],
    unit: 'un',
    default_portion_g: 46,
    default_portion_label: '1 unidade (46g)',
  },
  {
    name: 'Scrambled eggs',
    name_pt: 'Ovo mexido',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 10.0,
    carb_per_100g: 1.6,
    fat_per_100g: 11.1,
    fiber_per_100g: 0.0,
    calories_per_100g: 149,
    allergen_tags: ['egg', 'dairy'],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '2 ovos (100g)',
  },
  {
    name: 'Chicken salad',
    name_pt: 'Salpicão de frango',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 9.0,
    carb_per_100g: 8.0,
    fat_per_100g: 12.0,
    fiber_per_100g: 1.2,
    calories_per_100g: 178,
    allergen_tags: ['egg'],
    unit: 'g',
    default_portion_g: 100,
    default_portion_label: '2 colheres de servir (100g)',
  },
  {
    name: 'Tacacá',
    name_pt: 'Tacacá',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 4.0,
    carb_per_100g: 5.0,
    fat_per_100g: 1.0,
    fiber_per_100g: 0.5,
    calories_per_100g: 45,
    allergen_tags: ['shellfish'],
    unit: 'ml',
    default_portion_g: 400,
    default_portion_label: '1 cuia (400ml)',
  },

  // ──────────────────────────────────────────────
  // ADDITIONAL SNACKS / GRAINS (~8)
  // ──────────────────────────────────────────────
  {
    name: 'Cream cracker',
    name_pt: 'Biscoito cream cracker',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 9.0,
    carb_per_100g: 68.0,
    fat_per_100g: 13.5,
    fiber_per_100g: 3.0,
    calories_per_100g: 430,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 26,
    default_portion_label: '4 unidades (26g)',
  },
  {
    name: 'Maria biscuit',
    name_pt: 'Biscoito Maria',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 8.0,
    carb_per_100g: 74.0,
    fat_per_100g: 8.5,
    fiber_per_100g: 2.0,
    calories_per_100g: 404,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 24,
    default_portion_label: '4 unidades (24g)',
  },
  {
    name: 'Corn starch biscuit',
    name_pt: 'Biscoito de maisena',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 6.0,
    carb_per_100g: 75.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 1.5,
    calories_per_100g: 414,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 24,
    default_portion_label: '4 unidades (24g)',
  },
  {
    name: 'Oat bran',
    name_pt: 'Farelo de aveia',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 17.3,
    carb_per_100g: 54.8,
    fat_per_100g: 7.0,
    fiber_per_100g: 15.4,
    calories_per_100g: 346,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Wheat germ',
    name_pt: 'Gérmen de trigo',
    category: 'carb',
    store_section: 'grains',
    protein_per_100g: 23.2,
    carb_per_100g: 51.8,
    fat_per_100g: 9.7,
    fiber_per_100g: 13.2,
    calories_per_100g: 382,
    allergen_tags: ['gluten'],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Dried coconut (shredded)',
    name_pt: 'Coco ralado seco',
    category: 'snack',
    store_section: 'grains',
    protein_per_100g: 5.6,
    carb_per_100g: 26.3,
    fat_per_100g: 56.4,
    fiber_per_100g: 14.1,
    calories_per_100g: 611,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Prune',
    name_pt: 'Ameixa seca',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 2.2,
    carb_per_100g: 63.9,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.1,
    calories_per_100g: 240,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 25,
    default_portion_label: '3 unidades (25g)',
  },
  {
    name: 'Raisin',
    name_pt: 'Uva passa',
    category: 'snack',
    store_section: 'snacks',
    protein_per_100g: 3.1,
    carb_per_100g: 79.2,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.7,
    calories_per_100g: 299,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 25,
    default_portion_label: '1 colher de sopa (25g)',
  },

  // ──────────────────────────────────────────────
  // ADDITIONAL DAIRY (~3)
  // ──────────────────────────────────────────────
  {
    name: 'Sour cream',
    name_pt: 'Creme de leite azedo (sour cream)',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 2.4,
    carb_per_100g: 2.9,
    fat_per_100g: 20.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 198,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 25,
    default_portion_label: '1 colher de sopa (25g)',
  },
  {
    name: 'Dulce de leche',
    name_pt: 'Doce de leite',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 5.0,
    carb_per_100g: 55.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 315,
    allergen_tags: ['dairy'],
    unit: 'g',
    default_portion_g: 20,
    default_portion_label: '1 colher de sopa (20g)',
  },
  {
    name: 'Semi-skimmed milk',
    name_pt: 'Leite semidesnatado',
    category: 'dairy_alt',
    store_section: 'dairy',
    protein_per_100g: 3.3,
    carb_per_100g: 4.9,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.0,
    calories_per_100g: 46,
    allergen_tags: ['dairy'],
    unit: 'ml',
    default_portion_g: 200,
    default_portion_label: '1 copo (200ml)',
  },
  // ──────────────────────────────────────────────
  // FINAL ADDITIONS (~11)
  // ──────────────────────────────────────────────
  {
    name: 'Instant noodles',
    name_pt: 'Miojo (macarrão instantâneo)',
    category: 'prepared',
    store_section: 'grains',
    protein_per_100g: 9.0,
    carb_per_100g: 56.0,
    fat_per_100g: 17.0,
    fiber_per_100g: 2.0,
    calories_per_100g: 413,
    allergen_tags: ['gluten', 'soy'],
    unit: 'un',
    default_portion_g: 85,
    default_portion_label: '1 pacote (85g)',
  },
  {
    name: 'Pizza (frozen margherita)',
    name_pt: 'Pizza congelada (margherita)',
    category: 'prepared',
    store_section: 'frozen',
    protein_per_100g: 10.5,
    carb_per_100g: 30.0,
    fat_per_100g: 10.0,
    fiber_per_100g: 1.8,
    calories_per_100g: 253,
    allergen_tags: ['gluten', 'dairy'],
    unit: 'g',
    default_portion_g: 110,
    default_portion_label: '1 fatia (110g)',
  },
  {
    name: 'Sausage (hot dog)',
    name_pt: 'Salsicha',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 11.0,
    carb_per_100g: 3.0,
    fat_per_100g: 22.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 258,
    allergen_tags: [],
    unit: 'un',
    default_portion_g: 50,
    default_portion_label: '1 unidade (50g)',
  },
  {
    name: 'Bologna',
    name_pt: 'Mortadela',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 12.0,
    carb_per_100g: 3.5,
    fat_per_100g: 25.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 289,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 30,
    default_portion_label: '2 fatias (30g)',
  },
  {
    name: 'Pepperoni',
    name_pt: 'Pepperoni',
    category: 'protein',
    store_section: 'proteins',
    protein_per_100g: 22.5,
    carb_per_100g: 2.0,
    fat_per_100g: 40.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 460,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 28,
    default_portion_label: '6 fatias (28g)',
  },
  {
    name: 'Açaí with granola',
    name_pt: 'Açaí com granola',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 3.0,
    carb_per_100g: 32.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 2.5,
    calories_per_100g: 200,
    allergen_tags: ['tree_nuts'],
    unit: 'g',
    default_portion_g: 300,
    default_portion_label: '1 tigela (300g)',
  },
  {
    name: 'Tapioca with cheese',
    name_pt: 'Tapioca com queijo',
    category: 'prepared',
    store_section: 'prepared',
    protein_per_100g: 5.5,
    carb_per_100g: 18.0,
    fat_per_100g: 7.0,
    fiber_per_100g: 0.3,
    calories_per_100g: 157,
    allergen_tags: ['dairy'],
    unit: 'un',
    default_portion_g: 100,
    default_portion_label: '1 unidade (100g)',
  },
  {
    name: 'Barbecue sauce',
    name_pt: 'Molho barbecue',
    category: 'seasoning',
    store_section: 'condiments',
    protein_per_100g: 0.8,
    carb_per_100g: 40.0,
    fat_per_100g: 0.6,
    fiber_per_100g: 0.5,
    calories_per_100g: 166,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 15,
    default_portion_label: '1 colher de sopa (15g)',
  },
  {
    name: 'Hot sauce',
    name_pt: 'Molho de pimenta',
    category: 'seasoning',
    store_section: 'condiments',
    protein_per_100g: 0.5,
    carb_per_100g: 3.3,
    fat_per_100g: 0.4,
    fiber_per_100g: 0.7,
    calories_per_100g: 15,
    allergen_tags: [],
    unit: 'ml',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5ml)',
  },
  {
    name: 'Xylitol',
    name_pt: 'Xilitol',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 0.0,
    carb_per_100g: 100.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 240,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5g)',
  },
  {
    name: 'Erythritol',
    name_pt: 'Eritritol',
    category: 'seasoning',
    store_section: 'grains',
    protein_per_100g: 0.0,
    carb_per_100g: 100.0,
    fat_per_100g: 0.0,
    fiber_per_100g: 0.0,
    calories_per_100g: 0,
    allergen_tags: [],
    unit: 'g',
    default_portion_g: 5,
    default_portion_label: '1 colher de chá (5g)',
  },
] as const;
